---
# Experiment 19 and 20
## Covid Data Analysis & India Data Analysis
---
Name : Ayush Pathare  
PRN : 25070123266  
Class : E&TC A2

---

In [1]:
import pandas as pd
import numpy as np

In [32]:
data = pd.read_csv("/content/covid_19_data.csv")
print(data.head())

   SNo ObservationDate Province/State  Country/Region      Last Update  \
0    1      01/22/2020          Anhui  Mainland China  1/22/2020 17:00
1    2      01/22/2020        Beijing  Mainland China  1/22/2020 17:00
2    3      01/22/2020      Chongqing  Mainland China  1/22/2020 17:00
3    4      01/22/2020         Fujian  Mainland China  1/22/2020 17:00
4    5      01/22/2020          Gansu  Mainland China  1/22/2020 17:00

   Confirmed  Deaths  Recovered
0        1.0     0.0        0.0
1       14.0     0.0        0.0
2        6.0     0.0        0.0
3        1.0     0.0        0.0
4        0.0     0.0        0.0

In [3]:
data = data.drop(['SNo', 'Last Update'], axis = 1)
data.head()

  ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      01/22/2020          Anhui  Mainland China        1.0     0.0        0.0
1      01/22/2020        Beijing  Mainland China       14.0     0.0        0.0
2      01/22/2020      Chongqing  Mainland China        6.0     0.0        0.0
3      01/22/2020         Fujian  Mainland China        1.0     0.0        0.0
4      01/22/2020          Gansu  Mainland China        0.0     0.0        0.0

In [33]:
# Check Dataset Size Parameter
data.shape

(306429, 8)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ObservationDate  306429 non-null  object
 1   Province/State   228326 non-null  object
 2   Country/Region   306429 non-null  object
 3   Confirmed        306429 non-null  float64
 4   Deaths           306429 non-null  float64
 5   Recovered        306429 non-null  float64
dtypes: float64(3), object(3)
memory usage: 14.0+ MB

In [6]:
data['ObservationDate'] = data['ObservationDate'].astype('datetime64[ns]')
data['Confirmed'] = data['Confirmed'].astype('int64')
data['Deaths'] = data['Deaths'].astype('int64')
data['Recovered'] = data['Recovered'].astype('int64')

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ObservationDate  306429 non-null  datetime64[ns]
 1   Province/State   228326 non-null  object
 2   Country/Region   306429 non-null  object
 3   Confirmed        306429 non-null  int64
 4   Deaths           306429 non-null  int64
 5   Recovered        306429 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 14.0+ MB

In [7]:
data.head()

  ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      2020-01-22          Anhui  Mainland China          1       0          0
1      2020-01-22        Beijing  Mainland China         14       0          0
2      2020-01-22      Chongqing  Mainland China          6       0          0
3      2020-01-22         Fujian  Mainland China          1       0          0
4      2020-01-22          Gansu  Mainland China          0       0          0

In [34]:
# Number of Acive cases

data['Active'] = data['Confirmed'] - data['Deaths'] - data['Recovered']
data.head(50)

data.iloc[50:100]

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Active
50,51,01/23/2020,Heilongjiang,Mainland China,1/23/20 17:00,2.0,0.0,0.0,2.0
51,52,01/23/2020,Henan,Mainland China,1/23/20 17:00,5.0,0.0,0.0,5.0
52,53,01/23/2020,Hong Kong,Hong Kong,1/23/20 17:00,2.0,0.0,0.0,2.0
53,54,01/23/2020,Hubei,Mainland China,1/23/20 17:00,444.0,17.0,28.0,399.0
54,55,01/23/2020,Hunan,Mainland China,1/23/20 17:00,9.0,0.0,0.0,9.0
55,56,01/23/2020,Inner Mongolia,Mainland China,1/23/20 17:00,0.0,0.0,0.0,0.0
56,57,01/23/2020,Jiangsu,Mainland China,1/23/20 17:00,5.0,0.0,0.0,5.0
57,58,01/23/2020,Jiangxi,Mainland China,1/23/20 17:00,7.0,0.0,0.0,7.0
58,59,01/23/2020,Jilin,Mainland China,1/23/20 17:00,1.0,0.0,0.0,1.0
59,60,01/23/2020,Liaoning,Mainland China,1/23/20 17:00,3.0,0.0,0.0,3.0
60,61,01/23/2020,Macau,Macau,1/23/20 17:00,2.0,0.0,0.0,2.0
61,62,01/23/2020,Ningxia,Mainland China,1/23/20 17:00,1.0,0.0,0.0,1.0
62,63,01/23/2020,Qinghai,Mainland China,1/23/20 17:00,0.0,0.0,0.0,0.0
63,64,01/23/2020,Shaanxi,Mainland China,1/23/20 17:00,3.0,0.0,0.0,3.0
64,65,01/23/2020,Shandong,Mainland China,1/23/20 17:00,6.0,0.0,0.0,6.0
65,66,01/23/2020,Shanghai,Mainland China,1/23/20 17:00,16.0,0.0,0.0,16.0
66,67,01/23/2020,Shanxi,Mainland China,1/23/20 17:00,1.0,0.0,0.0,1.0
67,68,01/23/2020,Sichuan,Mainland China,1/23/20 17:00,8.0,0.0,0.0,8.0
68,69,01/23/2020,Taiwan,Taiwan,1/23/20 17:00,1.0,0.0,0.0,1.0
69,70,01/23/2020,Tianjin,Mainland China,1/23/20 17:00,4.0,0.0,0.0,4.0
70,71,01/23/2020,Tibet,Mainland China,1/23/20 17:00,0.0,0.0,0.0,0.0
71,72,01/23/2020,Washington,US,1/23/20 17:00,1.0,0.0,0.0,1.0
72,73,01/23/2020,Xinjiang,Mainland China,1/23/20 17:00,2.0,0.0,0.0,2.0
73,74,01/23/2020,Yunnan,Mainland China,1/23/20 17:00,2.0,0.0,0.0,2.0
74,75,01/23/2020,Zhejiang,Mainland China,1/23/20 17:00,27.0,0.0,0.0,27.0
75,76,01/23/2020,NaN,Japan,1/23/20 17:00,1.0,0.0,0.0,1.0
76,77,01/23/2020,NaN,Thailand,1/23/20 17:00,4.0,0.0,2.0,2.0
77,78,01/23/2020,NaN,South Korea,1/23/20 17:00,1.0,0.0,0.0,1.0
78,79,01/23/2020,NaN,Singapore,1/23/20 17:00,1.0,0.0,0.0,1.0
79,80,01/23/2020,NaN,Philippines,1/23/20 17:00,0.0,0.0,0.0,0.0
80,81,01/23/2020,NaN,Malaysia,1/23/20 17:00,0.0,0.0,0.0,0.0
81,82,01/23/2020,NaN,Vietnam,1/23/20 17:00,2.0,0.0,0.0,2.0
82,83,01/23/2020,NaN,Australia,1/23/20 17:00,0.0,0.0,0.0,0.0
83,84,01/23/2020,NaN,Mexico,1/23/20 17:00,0.0,0.0,0.0,0.0
84,85,01/23/2020,NaN,Brazil,1/23/20 17:00,0.0,0.0,0.0,0.0
85,86,01/23/2020,NaN,Colombia,1/23/20 17:00,0.0,0.0,0.0,0.0
86,87,01/23/2020,Unknown,China,1/23/20 17:00,0.0,0.0,0.0,0.0
87,88,01/23/2020,NaN,Kiribati,1/23/20 17:00,0.0,0.0,0.0,0.0
88,89,01/24/2020,Hubei,Mainland China,1/24/20 17:00,549.0,24.0,31.0,494.0
89,90,01/24/2020,Guangdong,Mainland China,1/24/20 17:00,53.0,0.0,2.0,51.0
90,91,01/24/2020,Zhejiang,Mainland China,1/24/20 17:00,43.0,0.0,1.0,42.0
91,92,01/24/2020,Beijing,Mainland China,1/24/20 17:00,36.0,0.0,1.0,35.0
92,93,01/24/2020,Chongqing,Mainland China,1/24/20 17:00,27.0,0.0,0.0,27.0
93,94,01/24/2020,Hunan,Mainland China,1/24/20 17:00,24.0,0.0,0.0,24.0
94,95,01/24/2020,Guangxi,Mainland China,1/24/20 17:00,23.0,0.0,0.0,23.0
95,96,01/24/2020,Shanghai,Mainland China,1/24/20 17:00,20.0,0.0,1.0,19.0
96,97,01/24/2020,Jiangxi,Mainland China,1/24/20 17:00,18.0,0.0,0.0,18.0
97,98,01/24/2020,Sichuan,Mainland China,1/24/20 17:00,15.0,0.0,0.0,15.0
98,99,01/24/2020,Shandong,Mainland China,1/24/20 17:00,15.0,0.0,0.0,15.0
99,100,01/24/2020,Anhui,Mainland China,1/24/20 17:00,15.0,0.0,0.0,15.0

In [35]:
# Last / Current Date

data['ObservationDate'].max()

'12/31/2020'

In [10]:
# Fetch the latest date data

latest_data = data[data['ObservationDate'] == data['ObservationDate'].max()]

latest_data.head()

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
305664,2021-05-29,NaN,Afghanistan,70111,2899,57281,9931
305665,2021-05-29,NaN,Albania,132297,2449,129215,633
305666,2021-05-29,NaN,Algeria,128456,3460,89419,35577
305667,2021-05-29,NaN,Andorra,13693,127,13416,150
305668,2021-05-29,NaN,Angola,34180,757,27646,5777

In [11]:
latest_data.shape

(765, 7)

In [12]:
latest_data['Country/Region'].value_counts()

Country/Region
Russia                83
US                    58
Japan                 49
India                 37
Colombia              34
                      ..
Venezuela              1
Vietnam                1
West Bank and Gaza     1
Hong Kong              1
Macau                  1
Name: count, Length: 195, dtype: int64

In [38]:
for names in latest_data['Country/Region'].unique():
  print(names)

# latest_data['Country/Region'].unique()

Afghanistan
Albania
Algeria
Andorra
Angola
Antigua and Barbuda
Argentina
Armenia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belize
Benin
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brunei
Bulgaria
Burkina Faso
Burma
Burundi
Cabo Verde
Cambodia
Cameroon
Central African Republic
Chad
Comoros
Congo (Brazzaville)
Congo (Kinshasa)
Costa Rica
Croatia
Cuba
Cyprus
Czech Republic
Denmark
Diamond Princess
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Eswatini
Ethiopia
Fiji
Finland
France
Gabon
Gambia
Georgia
Ghana
Greece
Grenada
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Holy See
Honduras
Hungary
Iceland
Indonesia
Iran
Iraq
Ireland
Israel
Ivory Coast
Jamaica
Jordan
Kazakhstan
Kenya
Kiribati
Kosovo
Kuwait
Kyrgyzstan
Laos
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
MS Zaandam
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Micronesia
Moldova
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Namibia
Nepal
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
Norway
Oman
Panama
Papua New Guinea
Paraguay
Philippines
Poland
Portugal
Qatar
Romania
Rwanda
Saint Kitts and Nevis
Saint Lucia
Saint Vincent and the Grenadines
Samoa
San Marino
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Solomon Islands
Somalia
South Africa
South Korea
South Sudan
Sri Lanka
Sudan
Suriname
Switzerland
Syria
Taiwan
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Trinidad and Tobago
Tunisia
Turkey
Uganda
United Arab Emirates
Uruguay
Uzbekistan
Vanuatu
Venezuela
Vietnam
West Bank and Gaza
Yemen
Zambia
Zimbabwe
Italy
Brazil
Russia
Mexico
Japan
US
Canada
Colombia
Peru
Spain
India
UK
Mainland China
Chile
Belgium
Netherlands
Australia
Pakistan
Germany
Sweden
Ukraine
Hong Kong
Macau

In [14]:
latest_data['Country/Region'].nunique() # gives the number of countires in the aove output

195

In [39]:
# Count of cases in each country

countries = latest_data.groupby("Country/Region")[["Confirmed", "Deaths", "Recovered", "Active"]].sum()
countries = countries.reset_index()
countries.head()

  Country/Region  Confirmed  Deaths  Recovered  Active
0    Afghanistan      70111    2899      57281    9931
1        Albania     132297    2449     129215     633
2        Algeria     128456    3460      89419   35577
3        Andorra      13693     127      13416     150
4         Angola      34180     757      27646    5777

In [16]:
countries[countries['Country/Region'] == 'India']

   Country/Region  Confirmed  Deaths  Recovered   Active
78          India   27894800  325972   25454320  2114508

In [17]:
countries[countries['Country/Region'] == 'US']

    Country/Region  Confirmed  Deaths  Recovered    Active
182             US   33251939  594306          0  32657633

In [18]:
countries[countries['Country/Region'] == 'Mainland China']

     Country/Region  Confirmed  Deaths  Recovered  Active
107  Mainland China      91072    4636      86117     319

---
### Using World Map -

In [19]:
import plotly.express as px

In [20]:
world_map = px.choropleth(countries, locations = "Country/Region", locationmode = "country names", color = "Confirmed", color_continuous_scale = "mint", range_color = [0,10000000])

world_map

In [21]:
# Top countries having maximum confirmed ad recovered areas

top = latest_data.groupby("Country/Region")[['Confirmed', 'Recovered']].sum().reset_index()
top = top.sort_values(['Confirmed'], ascending = False)

top_20 = top.head(20)
top_20

     Country/Region  Confirmed  Recovered
182              US   33251939          0
78            India   27894800   25454320
23           Brazil   16471600   14496224
60           France    5719877     390878
180          Turkey    5235978    5094279
144          Russia    4995613    4616422
181              UK    4496823      15481
84            Italy    4213055    3845087
6         Argentina    3732263    3288467
64          Germany    3684672    3479700
165           Spain    3668658     150376
36         Colombia    3363061    3141549
80             Iran    2893218    2425033
140          Poland    2871371    2636675
116          Mexico    2411503    1924865
184         Ukraine    2257904    2084477
138            Peru    1947555    1897522
79        Indonesia    1809926    1659974
126     Netherlands    1671967      26810
44   Czech Republic    1660935    1617498

---
# Analysis of India's Data
---
Name - Ayush Pathare  
PRN - 25070123166

---

In [22]:
india = data[data['Country/Region'] == 'India']
india

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
446,2020-01-30,NaN,India,1,0,0,1
509,2020-01-31,NaN,India,1,0,0,1
567,2020-02-01,NaN,India,1,0,0,1
629,2020-02-02,NaN,India,2,0,0,2
696,2020-02-03,NaN,India,3,0,0,3
...,...,...,...,...,...,...,...
306351,2021-05-29,Tripura,India,50739,507,43190,7042
306366,2021-05-29,Unknown,India,0,0,0,0
306377,2021-05-29,Uttar Pradesh,India,1688152,20208,1621743,46201
306378,2021-05-29,Uttarakhand,India,327112,6360,289642,31110
306406,2021-05-29,West Bengal,India,1354956,15268,1237290,102398

In [23]:
# Find the total number of unique states
india['Province/State'].nunique()

38

In [24]:
# Find the names of unique  states
india['Province/State'].unique()

array([nan, 'Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadar Nagar Haveli', 'Delhi', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
       'Karnataka', 'Kerala', 'Ladakh', 'Madhya Pradesh', 'Maharashtra',
       'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
       'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Telangana', 'Tripura', 'Unknown', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal', 'Dadra and Nagar Haveli and Daman and Diu',
       'Lakshadweep'], dtype=object)

In [25]:
# fill NaN wit mode of states
india['Province/State'] = india['Province/State'].fillna(india['Province/State'].mode())
india

/tmp/ipykernel_18980/2581282926.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
446,2020-01-30,NaN,India,1,0,0,1
509,2020-01-31,NaN,India,1,0,0,1
567,2020-02-01,NaN,India,1,0,0,1
629,2020-02-02,NaN,India,2,0,0,2
696,2020-02-03,NaN,India,3,0,0,3
...,...,...,...,...,...,...,...
306351,2021-05-29,Tripura,India,50739,507,43190,7042
306366,2021-05-29,Unknown,India,0,0,0,0
306377,2021-05-29,Uttar Pradesh,India,1688152,20208,1621743,46201
306378,2021-05-29,Uttarakhand,India,327112,6360,289642,31110
306406,2021-05-29,West Bengal,India,1354956,15268,1237290,102398

In [26]:
india['Province/State'] = india['Province/State'].replace('Unknown', india['Province/State'].mode()[0])
india

/tmp/ipykernel_18980/4190921802.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
446,2020-01-30,NaN,India,1,0,0,1
509,2020-01-31,NaN,India,1,0,0,1
567,2020-02-01,NaN,India,1,0,0,1
629,2020-02-02,NaN,India,2,0,0,2
696,2020-02-03,NaN,India,3,0,0,3
...,...,...,...,...,...,...,...
306351,2021-05-29,Tripura,India,50739,507,43190,7042
306366,2021-05-29,Andaman and Nicobar Islands,India,0,0,0,0
306377,2021-05-29,Uttar Pradesh,India,1688152,20208,1621743,46201
306378,2021-05-29,Uttarakhand,India,327112,6360,289642,31110
306406,2021-05-29,West Bengal,India,1354956,15268,1237290,102398

In [27]:
india_latest_data = india[india['ObservationDate'] == india['ObservationDate'].max()]
india_latest_data

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
305855,2021-05-29,Andaman and Nicobar Islands,India,6964,113,6660,191
305856,2021-05-29,Andhra Pradesh,India,1671742,10738,1487382,173622
305873,2021-05-29,Arunachal Pradesh,India,26778,114,22746,3918
305874,2021-05-29,Assam,India,403623,3245,344083,56295
305896,2021-05-29,Bihar,India,704173,5052,678036,21085
305930,2021-05-29,Chandigarh,India,59740,740,56534,2466
305937,2021-05-29,Chhattisgarh,India,967645,12979,911752,42914
305956,2021-05-29,Dadra and Nagar Haveli and Daman and Diu,India,10214,4,9877,333
305960,2021-05-29,Delhi,India,1424646,24073,1387538,13035
305996,2021-05-29,Goa,India,154419,2597,136766,15056
306012,2021-05-29,Gujarat,India,805617,9790,757124,38703
306018,2021-05-29,Haryana,India,753937,8132,722711,23094
306025,2021-05-29,Himachal Pradesh,India,188604,3086,168529,16989
306051,2021-05-29,Jammu and Kashmir,India,286684,3841,243588,39255
306054,2021-05-29,Jharkhand,India,336240,4958,320336,10946
306072,2021-05-29,Karnataka,India,2567449,28298,2189064,350087
306075,2021-05-29,Kerala,India,2494385,8455,2252505,233425
306100,2021-05-29,Ladakh,India,18448,187,16658,1603
306101,2021-05-29,Lakshadweep,India,7631,31,5622,1978
306121,2021-05-29,Madhya Pradesh,India,777349,7959,738491,30899
306127,2021-05-29,Maharashtra,India,5713215,94030,5339838,279347
306129,2021-05-29,Manipur,India,48850,776,40044,8030
306142,2021-05-29,Meghalaya,India,34448,551,26156,7741
306156,2021-05-29,Mizoram,India,11988,36,8863,3089
306168,2021-05-29,Nagaland,India,21371,350,16039,4982
306212,2021-05-29,Odisha,India,747143,2686,658646,85811
306246,2021-05-29,Puducherry,India,102896,1497,88246,13153
306250,2021-05-29,Punjab,India,562831,14305,506349,42177
306260,2021-05-29,Rajasthan,India,936162,8251,871283,56628
306309,2021-05-29,Sikkim,India,14907,247,10829,3831
306330,2021-05-29,Tamil Nadu,India,2039716,23261,1706298,310157
306334,2021-05-29,Telangana,India,574026,3247,533862,36917
306351,2021-05-29,Tripura,India,50739,507,43190,7042
306366,2021-05-29,Andaman and Nicobar Islands,India,0,0,0,0
306377,2021-05-29,Uttar Pradesh,India,1688152,20208,1621743,46201
306378,2021-05-29,Uttarakhand,India,327112,6360,289642,31110
306406,2021-05-29,West Bengal,India,1354956,15268,1237290,102398

In [28]:
top_state = india_latest_data.groupby('Province/State')[['Confirmed', 'Recovered']].sum().reset_index()
top_state = top_state.sort_values(['Confirmed'], ascending = False)
top_state.head(20)

    Province/State  Confirmed  Recovered
20     Maharashtra    5713215    5339838
15       Karnataka    2567449    2189064
16          Kerala    2494385    2252505
30      Tamil Nadu    2039716    1706298
33   Uttar Pradesh    1688152    1621743
1   Andhra Pradesh    1671742    1487382
8            Delhi    1424646    1387538
35     West Bengal    1354956    1237290
6     Chhattisgarh     967645     911752
28       Rajasthan     936162     871283
10         Gujarat     805617     757124
19  Madhya Pradesh     777349     738491
11         Haryana     753937     722711
25          Odisha     747143     658646
4            Bihar     704173     678036
31       Telangana     574026     533862
27          Punjab     562831     506349
3            Assam     403623     344083
14       Jharkhand     336240     320336
34     Uttarakhand     327112     289642

In [29]:
top_state['Confirmed'].max()

5713215

In [30]:
top_state[top_state['Confirmed'] == top_state['Confirmed'].max()]['Province/State'].values[0]

'Maharashtra'

In [31]:
top_state[top_state['Confirmed'] == top_state['Confirmed'].min()]['Province/State'].values[0]

'Andaman and Nicobar Islands'